### ISSUE TITLE
Scalene not working on Windows because ITIMER_PROF in signal is not supported

### ISSUE THREAD

**Issue by jimcarst** [emeryberger/scalene#4]
Hi,

For your information, I would like to report that scalene is not working on Windows 10. I get the following error message when I try running it:

```py
  Traceback (most recent call last):
  File "C:\...\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\...\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\...\anaconda3\lib\site-packages\scalene\__main__.py", line 1, in <module>
    from scalene import scalene
  File "C:\...\anaconda3\lib\site-packages\scalene\scalene.py", line 239, in <module>
    scalene.main()
  File "C:\...\anaconda3\lib\site-packages\scalene\scalene.py", line 218, in main
    profiler = scalene(os.path.join(program_path, os.path.basename(sys.argv[0])))
  File "C:\...\anaconda3\lib\site-packages\scalene\scalene.py", line 75, in __init__
    signal.signal(signal.SIGPROF, self.cpu_signal_handler)
AttributeError: module 'signal' has no attribute 'SIGPROF'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\...\anaconda3\lib\site-packages\scalene\scalene.py", line 199, in exit_handler
    scalene.disable_signals()
  File "C:\...\anaconda3\lib\site-packages\scalene\scalene.py", line 192, in disable_signals
    signal.signal(signal.ITIMER_PROF, signal.SIG_IGN)
AttributeError: module 'signal' has no attribute 'ITIMER_PROF'

```

As reported [here](https://github.com/nvdv/vprof/issues/62), apparently signal is not suppored fully on Windows.

**Comment by emeryberger** [comment]
I have added a check that indicates that Windows is not supported (unfortunately).
