### ISSUE TITLE
[CentOS 7] Throw PermissionError at CPU Only mode

### ISSUE THREAD

**Issue by Insutanto** [emeryberger/scalene#62]
Throw PermissionError at CPU Only mode when I run the `testme.py` without `sudo`

====================================

Scalene: An exception of type PermissionError occurred. Arguments:
(13, 'Permission denied')
Traceback (most recent call last):
  File "/data/project/py_venv/scalene/lib/python3.7/site-packages/scalene/scalene.py", line 1382, in main
    if profiler.output_profiles():
  File "/data/project/py_venv/scalene/lib/python3.7/site-packages/scalene/scalene.py", line 1309, in output_profiles
    console.save_text("/dev/stdout", styles=True)
  File "/data/project/py_venv/scalene/lib/python3.7/site-packages/rich/console.py", line 967, in save_text
    with open(path, "wt", encoding="utf-8") as write_file:
PermissionError: [Errno 13] Permission denied: '/dev/stdout'

**Comment by Insutanto** [comment]
I have a PR for this issue: #63

**Comment by emeryberger** [comment]
Merged - thanks!
