### ISSUE TITLE
AttributeError: type object 'scalene' has no attribute 'current_footprint'

### ISSUE THREAD

**Issue by wxkdesky** [emeryberger/scalene#8]
When I run test file for both cpu&mem profiling, 
**LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc python -m scalene test/testme.py**
error occurs
scalene: An exception of type AttributeError occurred. Arguments:
("type object 'scalene' has no attribute 'current_footprint'",)
Traceback (most recent call last):
  File "/work/scalene/scalene/scalene.py", line 261, in main
    exec(code, the_globals)
  File "test/testme.py", line 7, in <module>
    arr = [i for i in range(1,1000)]
  File "test/testme.py", line 7, in <listcomp>
    arr = [i for i in range(1,1000)]
  File "/work/scalene/scalene/scalene.py", line 153, in free_signal_handler
    scalene.current_footprint -= 1
**AttributeError: type object 'scalene' has no attribute 'current_footprint'**

**Comment by emeryberger** [comment]
Fixed (variable removed, for now). Thanks!
