### ISSUE TITLE
seg fault running scalene on TensorFlow script

### ISSUE THREAD

**Issue by jaltmayerpizzorno** [emeryberger/scalene#81]
**Describe the bug**
libscalene.so seg faults running on script that uses TensorFlow

**To Reproduce**
Run scalene on this excerpt:
```
import tensorflow.keras as keras

layer_in = keras.Input(shape=(608, 608, 3))
layer_0 = keras.layers.ZeroPadding2D(((1,1),(1,1)))(layer_in)
layer_0 = keras.layers.Conv2D(32, 3, strides=1, use_bias=False, name='conv_0')(layer_0)
```

I traced it back to glibc's `dlerror.c` having registered a TSD key (`pthread_key_create`) whose
destructor attempts to free memory at a time when the heap was already destroyed.  This is
the backtrace:

```
#0  0x00007ffff5fc2a52 in Sampler<1048538>::sample (this=0x7ffe5c025110, sz=32) at ./include/sampler.hpp:31
#1  SampleHeap<1048538ul, RepoMan<4096, OneSource> >::free (this=0x7ffe5c025000, ptr=0x7fff434130c0) at ./include/sampleheap.hpp:90
#2  HL::ThreadSpecificHeap<S>::free (this=0x7ffff7fc8300 <getTheCustomHeap()::thang+33554560>, ptr=0x7fff434130c0)
    at Heap-Layers/heaps/threads/threadspecificheap.h:56
#3  0x00007ffff5fc23e1 in TheCustomHeap::free (this=0x7ffff5fc8280 <getTheCustomHeap()::thang>, ptr=0x7fff434130c0)
    at libscalene.cpp:109
#4  xxfree (ptr=0x7fff434130c0) at libscalene.cpp:302
#5  0x00007ffff5fc30d5 in customfree (ptr=0x7fff434130c0) at Heap-Layers/wrappers/wrapper.cpp:137
#6  0x00007ffff5d7e7c4 in free_key_mem (mem=0x7fff434130c0) at dlerror.c:230
#7  0x00007ffff5d8b5a1 in __nptl_deallocate_tsd () at pthread_create.c:301
#8  0x00007ffff5d8c62a in __nptl_deallocate_tsd () at pthread_create.c:256
#9  start_thread (arg=<optimized out>) at pthread_create.c:488
#10 0x00007ffff5ec8103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I issued [a pull request](https://github.com/emeryberger/Heap-Layers/pull/30) with a suggested repair on `Heap-Layers`.

**Comment by emeryberger** [comment]
Merged the PR (https://github.com/emeryberger/Heap-Layers/pull/30#event-3831898697) and verified that this works. Will post an update to pypi shortly - thanks!

**Comment by jaltmayerpizzorno** [comment]
Thank you!
